FROM eclipse-temurin:17-jdk-focal

WORKDIR /app

RUN apt-get -y update
RUN apt-get -y install dos2unix

COPY .mvn/ .mvn
COPY mvnw pom.xml ./

RUN dos2unix mvnw
RUN chmod +x mvnw
RUN ./mvnw dependency:go-offline

COPY src ./src

CMD ["./mvnw", "spring-boot:run"]

EXPOSE 8080